      <div class="adpage-title">
        <div class="title" >Deal Status</div>
      </div>
      <div class="user-strip">
			<?php echo $this->links; ?>
        <div class="clear"></div>
        <div style="margin-top:12px;margin-bottom:15px;">
        	<?php echo $this->addOption; ?>
        </div>
        <div class="clear"></div>
      </div>
      
      <?php if (count($this->messages)) : ?>
                 <br/>
                <div class="errorMSG-autoh">
                	<ul id="messages">
                    	<?php foreach ($this->messages as $message) : ?>
                            <li><?php echo $this->escape($message); ?></li>
                        <?php endforeach; ?>
                	</ul>
                </div>
      <?php endif; ?>
     
      <br/>
      