       	<div class="adpage-title">
        	<div class="title" >Add Model</div>
        </div>
        
        <div class="user-strip">
        	<?php echo $this->links; ?>
            <div class="clear"></div>
        </div>

		
        <!--#quick links-->
        <div class="option-box-top">
        	<div class="heading">VEHICLE MODELS</div>
        </div>
        <div class="option-box-middle">
			<div class="quick-links-wrapper">
             	<div id="navcontainer">
                   <?php 
				   		echo $this->form ;
				   ?>
                <div class="clear"></div>
                </div>   
            </div>
        </div>
        <div class="option-box-bottom"></div>
        <br />
        <!--$quick links-->
        
        <br />
        <!-- $Contents -->