<div class="bodyTagline"><img src="<?php echo $this->baseUrl();?>/images/tagline.png" alt="Maximizing your sales &amp; Profits" width="516" height="65" /></div>				
		
		<div class="colL"><img src="<?php echo $this->baseUrl();?>/images/car1.png" alt="" width="406" height="207" /></div>
		<div class="colR">
		
			<div id='scrollArea'>
            
                <p class="txt-12-grey">
                
                <?php echo $this->pageContent;?>
                </p>
			
			  </div>
		
		
		</div>
		<div class="clear"></div>       