       	<div class="adpage-title">
        	<div class="title" >Role Permissions</div>
        </div>
        
        <div class="user-strip">
        	<?php echo $this->links; ?>
            <div class="clear"></div>
        </div>

		
        
       <?php
	   		echo $this->topWrapper1;
       	  	echo $this->subform;
			echo $this->bottomWrapper1;
	   ?>
       
       <br/>
        <?php
	   		echo $this->topWrapper2;
       	  	echo $this->form;
			echo $this->bottomWrapper2;
	   ?>
       <br/>
       <br/>
     