	<div class="header">

		<div class="headerMain">
		
		<div class="logolink Fl"><a href="<?php echo $this->baseUrl().'/index';?>"><img src="<?php echo $this->baseUrl('images/blank.gif');?>" alt="" width="277" height="45" border="0" /></a></div>
		
		<div class="clear"></div>

	

		</div><!--headerMain-->
		
		<div class="mainNavCon">
		
			
			
			<div class="clear"></div>
		
		</div><!--mainNavCon-->

	</div><!--header-->
	
	