<div class="footer">
	
		<a href="#" >Home</a> | <a href="#">Browse Inventory</a> | <a href="#">Dealer Packages</a> | <a href="#">About us</a> | <a href="#">Contact us</a><br />
Copyright 2010 <span class="black">Add on Cars</span>. All rights Reserved. <u><a href="#">Terms of Use</a></u> | <u><a href="#">Privacy Policy</a></u><br /><br />
Mockup by: <a href="http://medialinkers.com">Medialinkers</a>
	
	</div>