<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
 <?php
    echo $this->headTitle();
	
    echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');
	echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style-02.css');
    ?>
<body>

	<?php echo $this->render('admin_header.phtml') ?>
	
	<div class="wrapper mar55B">
	
			<?php echo $this->layout()->content; ?>
            	
		<div class="clear"></div>
	
	</div><!--wrapper-->
	
	<?php echo $this->render('footer.phtml'); ?>
<!--footer-->
	

</body>
</html>
