<div class="ad-midContainer"> 
  <!-- #Contents -->
  
  <div class="adpage-title">
    <div class="title">DashBoard</div>
  </div>
  <div class="user-strip">
    <div class="user-name"> Welcome :  <?php $auth = Zend_Auth::getInstance(); $identity = $auth->getIdentity(); $uname = $identity['uname']; echo strtoupper($uname); ?> </div>
    <div class="logout"><a href="<?php echo $this->baseUrl() ;?>/admin/logout">Logout</a></div>
    <div class="clear"></div>
  </div>
  
  <!-- #Alert Msgs-->
  <!-- $Alert Msgs-->
  
  
  <br />
  
  <!-- #Statistices-->
  <!-- $Statistices-->
  
  <br />

  <div class="option-box-top2"></div>
   
  <div class="option-box-middle">
  
    <div class="option-heading ">Deal Management</div>
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
	   <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/deal/adminindex" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/deals.png" width="32" height="32" /> </a>
        	<div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/deal/adminindex" class="icon-text">Deals</a></div>
       </div>
	   <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/commission/adminindex" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/commissions-icon.png" width="32" height="32" /> </a>
        	<div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/commission/adminindex" class="icon-text">Commissions</a></div>
       </div>
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper --> 
  
    
    <div class="option-heading ">Vehicle Options</div>  
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/make/adminindex" class="icon-text"><img src="<?php echo $this->baseUrl() ; ?>/images/make.png" width="32" height="32" /></a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/make/adminindex" class="icon-text">Make</a></div>
      </div>
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/carmodel/adminindex" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/models.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/carmodel/adminindex" class="icon-text">Models</a></div>
      </div>
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/pricemodifier/index"> <img src="<?php echo $this->baseUrl() ; ?>/images/pricemodifier.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/pricemodifier/index"  class="icon-text">Price Modifier</a></div>
      </div>
      
  
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/dealerpartcategoriessettings/edit"> <img src="<?php echo $this->baseUrl() ; ?>/images/Category.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/dealerpartcategoriessettings/edit"  class="icon-text">Category</a></div>
      </div>
     
   
  
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/dealermanufacturersettings/edit"> <img src="<?php echo $this->baseUrl() ; ?>/images/manufacturer.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/dealermanufacturersettings/edit"  class="icon-text">Manufacturer</a></div>
      </div>
     
      
    
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/dealerpartsettings/index"> <img src="<?php echo $this->baseUrl() ; ?>/images/exclusion.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/dealerpartsettings/index"  class="icon-text">Dealer Part Settings</a></div>
      </div>
     
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper -->
	
	 
    <!-- $icon-wrapper --> 
    <div class="option-heading ">Order Management</div>
    
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/orders/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/order.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/orders/index" class="icon-text">Orders</a></div>
      </div>
	  <div class="icons-box"> <a href="#" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/partlist_icon.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="#" class="icon-text">Retail Partlist</a></div>
      </div>
	  <div class="icons-box"> <a href="#" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/product_lookup.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="#" class="icon-text">Products Lookup</a></div>
      </div>
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper --> 
    
	
	
    <div class="option-heading ">Tecnical Department</div>
    
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/partsinstallation/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/technical_icon.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/partsinstallation/index" class="icon-text">Parts Installation</a></div>
      </div>
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper --> 
	
	
	<!-- $icon-wrapper -->
    
    <div class="option-heading ">User Managment Options</div>  
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
   	  
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/user/adminindex" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/user-icon.png" width="32" height="32"> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/user/adminindex" class="icon-text">Users</a></div>
      </div>
      
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/roles/listrole" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/roles-icon.png" width="32" height="32"> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/roles/listrole" class="icon-text">User Roles</a></div>
      </div>
   	  
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/permissions/list" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/permissions-icon.png" width="32" height="32"> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/permissions/list" class="icon-text">Role Permissions</a></div>
      </div>
      
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/user/adminindex" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/user-icon.png" width="32" height="32"> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/user/adminindex" class="icon-text">Pre-build Permissions</a></div>
      </div>
    
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/dealerdefaults/edit" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/permissions-icon.png" width="32" height="32"> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/dealerdefaults/edit" class="icon-text">My Account</a></div>
      </div>
     
     <!--
      <div class="icons-box"> <img src="<?php // echo $this->baseUrl() ;?>/admin-images/user-settings.png" width="32" height="32">
        <div class="icon-text"> Users Settings</div>
      </div>
      
      <div class="icons-box"> <a href="<?php //echo $this->baseUrl() ;?>/role" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/roles-icon.png" width="32" height="32"> </a>
        <div class="icon-text"> <a href="<?php //echo $this->baseUrl() ;?>/role" class="icon-text">Roles</a></div>
      </div>
      <div class="icons-box"> <a href="<?php //echo $this->baseUrl() ;?>/resource" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/performance-icon.png" width="32" height="32"> </a>
        <div class="icon-text"> <a href="<?php //echo $this->baseUrl() ;?>/resource" class="icon-text">AddOnCars Resources</a></div>
      </div>
      <div class="icons-box"> <a href="<?php //echo $this->baseUrl() ;?>/accessrules" class="icon-text"> <img src="<?php echo $this->baseUrl() ;?>/admin-images/access-rules-icon.png" width="32" height="32"> </a>
        <div class="icon-text"> <a href="<?php //echo $this->baseUrl() ;?>/accessrules" class="icon-text">Access rules</a></div>
      </div>
      -->
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper -->
    
    <!-- $icon-wrapper -->
    
    <div class="option-heading ">Reports</div>
    
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/dealerreports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/reporte.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/dealerreports/index" class="icon-text">Dealer Performance</a></div>
      </div>
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/salesreports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/vehicle_sale.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/salesreports/index" class="icon-text">Sales Performance</a></div>
      </div>
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/partreports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/vehicle-accessories.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/partreports/index" class="icon-text">Parts Performance</a></div>
      </div>
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/reports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/reports-overview.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/profitreports/index" class="icon-text">Profitabilty</a></div>
      </div>
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/reports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/profit_icon.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/profitreports/index" class="icon-text">Sold Products</a></div>
      </div>
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/reports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/model_year_icon.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/modelyearreport/index" class="icon-text">Model Year Parts</a></div>
      </div>
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/reports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/reports-overview.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/partusagereport/index" class="icon-text">Parts Usage</a></div>
      </div>
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/reports/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/reports-overview.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/vehiclepartreport/index" class="icon-text">Vehicle Parts</a></div>
      </div>
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper --> 
    
    <!-- $icon-wrapper -->
    
    <div class="option-heading ">Templates</div>
    
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
      
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/emailtemplete/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/template.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/emailtemplete/index" class="icon-text">Account Activation Email</a></div>
      </div>
	  <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/backgrounds/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/background_icon.png" width="32" height="32" /> </a>
        <div class="icon-text"> <a href="<?php echo $this->baseUrl() ;?>/backgrounds/index" class="icon-text">Canves Backgrounds</a></div>
      </div>
	  
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper --> 
    
    <!-- $icon-wrapper -->
    
    <div class="option-heading ">Content Management</div>
    
    <!-- #icon-wrapper -->
    <div class="icon-wrapper">
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/pagecontent/index" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/template.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/pagecontent/index" class="icon-text">Index</a></div>
      </div>
      
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/pagecontent/aboutus" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/template.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/pagecontent/aboutus" class="icon-text">About us</a></div>
      </div>
      
      <div class="icons-box"> <a href="<?php echo $this->baseUrl() ;?>/pagecontent/contactus" class="icon-text"> <img src="<?php echo $this->baseUrl() ; ?>/images/template.png" width="32" height="32" /> </a>
        <div class="icon-text"><a href="<?php echo $this->baseUrl() ;?>/pagecontent/contactus" class="icon-text">Contact us</a></div>
      </div>
      
      <div class="clear"></div>
    </div>
    <!-- $icon-wrapper --> 
  </div>
  
  <div class="option-box-bottom"></div>
 
  <br>
  <!-- $Contents --> 
</div>
