<?php
	
	function urlWorker($trimId , $modelId , $oldUrlArr ){
		$urlArr = array('trimId'=>$trimId , 'modelId'=>$modelId);
		$arr    = array_merge($oldUrlArr , $urlArr);
		$urlStr = Zend_Json::encode($arr);
		return base64_encode($urlStr);	
	}
	
	
?>
<div class="popup" id="menu1"  style="display:none;" ></div>
<div class="modelContainer">
	<div class="top"><img src="<?php echo $this->baseUrl() ; ?>/images/car-color-option-images/top.png" width="901" height="5" alt="" /></div>
	<div class="mid">
	<div class="midContainer">
	<div class="topheading">
	<div class="leftheading"><img src="<?php echo $this->baseUrl() ; ?>/images/car-color-option-images/heading.png" width="252" height="20" /></div>
	<div class="rightlink"><span class="red15"><a href="<?php echo $this->url(array('controller'=>'presentation','action'=>'makes')) ?>">Start Over</a> &gt; <a href="<?php echo $this->url(array('controller'=>'presentation','action'=>'makes','q'=>$this->oldUrl)) ?>">Make</a></span></div>
	<div class="clear"></div>
	</div>
	<div class="contenContainer">
	<div class="logobar">
	<div class="logo"><img src="<?php echo $this->baseUrl() ; ?>/images/car-color-option-images/honda.png" width="71" height="45" /></div>
	<div class="txt">Make: <?php echo $this->year; ?></div>
	<div class="clear"></div>
	</div>
	<div class="modelListContainer">
	<ul>
	
    <?php foreach ($this->models as $entry): ?>
                <?php if(count($entry->getTrims()) > 0){ ?>
                    <div class="popup" id="<?php echo $this->escape($entry->getModelId()) ?>"  style="display:none;" >
                      <table width="140" topmargin="0"  border="0" cellpadding="0" cellspacing="0">
                        <tr>
                          <td colspan="2" valign="top"><span class="style3">Select Trim</span></td>
                          <td align="right" valign="top"><img src="<?php echo $this->baseUrl() ; ?>/images/Button-Close_32.png" border="0"  width="10" height="10" onclick="hide_menu('menu1');" ></td>
                        </tr>
                        <!--years loop start-->
                        <?php
						$trims	=	$entry->getTrims();
						 foreach ($trims as $trim): ?>
                        <tr>
                          <td width="30">&nbsp;</td>
                          <td align="left"><a href="<?php echo $this->baseUrl()?>/presentation/colors/q/<?php echo urlWorker( $trim->getTrimId(),$entry->getModelId() , $this->oldUrlArr ); ?>" class="arial-12-black"> <?php echo $this->escape($trim->getTrimName()) ?> </a></td>
                          <td>&nbsp;</td>
                        </tr>
                        <?php endforeach ?>
                        <!--years loop end-->
                      </table>
                    </div>
    <li>  
   <div class="modelbox">
	<div class="top"><a href="" onmouseover="display_menu(this,'<?php echo $this->escape($entry->getModelId()) ?>');"><img src="<?php echo $this->baseUrl() ; ?>/assets/models/<?php echo $this->escape($entry->getModelImage()) ?>" width="147" height="113" /></a></div>
	<div class="bottom"><?php echo $this->escape($entry->getModelName()) ?></div>
	</div>
	</li>
    <?php } ?>
    
	 <?php endforeach ?>
	<div class="clear"></div>
	</ul>
	<div class="clear"></div>
	</div>
	
	</div>
	</div>
	</div>
	<div class="bottom"><img src="<?php echo $this->baseUrl() ; ?>/images/car-color-option-images/bottom.png" width="901" height="6" alt="" /></div>
	
	</div>
