<div class="colorContainer">
	<div class="top"><img src="<?php echo $this->baseUrl() ;?>/images/car-color-option-images/top.png" width="901" height="5" alt="" /></div>
	<div class="mid">
        <div class="ad-midContainer">
        <!-- #Contents -->
        
       	<div class="adpage-title">
        	<div class="title" >Add Role</div>
        </div>
        
        <div class="user-strip">
        	<div class="user-name">
           	 	<a href="<?php echo $this->baseUrl() ;?>/main/">Dashboard</a> >> <a href="<?php echo $this->baseUrl() ;?>/carmodel/adminindex/">Models</a>
            </div>
            <div class="logout"><a href="<?php echo $this->baseUrl() ;?>/admin/logout">Logout</a></div>
            <div class="clear"></div>
        </div>

		
        <!--#quick links-->
        <div class="option-box-top">
        	<div class="heading"></div>
        </div>
        <div class="option-box-middle">
			<div class="quick-links-wrapper">
             	<div id="navcontainer">
                     <table width="740" border="0" cellspacing="0" cellpadding="8">
                 
                 
                  <tr>
                    <td height="5" colspan="5"></td>
                   
                  </tr>
                  <tr class="blck15" bgcolor="" >
                    <td width="100" height="35"><span class="arial-12-black"></span></td>
                    <td width="540" class="arial-12-black"><?php echo $this->form ;?></td>
                    <td width="100" ></td>
                  </tr>
                </table>
                    <div class="clear"></div>
                    </div>   
            </div>
        </div>
        <div class="option-box-bottom"></div>
        <br />
        <!--$quick links-->
        
        <!--#form --><!--$form-->
        
        <br />
        <!-- $Contents -->
        </div>
	</div>
	</div>